spring:
    application:
        name: cloth-coordination
    devtools:
        restart:
            enabled: false
    sql:
        init:
            mode: always
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:~/cloth;AUTO_SERVER=TRUE
        username: sa
        password: password

    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                connection:
                    autocommit: false
        open-in-view: false
        defer-datasource-initialization: true

server:
    port: 8080
    tomcat:
        uri-encoding: utf-8